modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/pau101/Fairy-Lights/issues"
license="MIT"
[[mods]]
	modId="fairylights"
	version="${version}"
	displayName="Fairy Lights"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fairy-lights"
	authors="pau101"
	description="Fairy Lights introduces decorative string lights, bunting, garland, and more!"
	logoFile="logo.png"
[[dependencies.fairylights]]
	modId="forge"
	mandatory=true
	versionRange="[34,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.fairylights]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16,1.17)"
	ordering="NONE"
	side="BOTH"
