modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/pau101/Fairy-Lights/issues"
license="MIT"
[[mods]]
	modId="fairylights"
	version="6.0.0"
	displayName="Fairy Lights"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fairy-lights"
	authors="pau101"
	description="Fairy Lights introduces decorative string lights, bunting, garland, and more!"
	logoFile="logo.png"
[[dependencies.fairylights]]
	modId="forge"
	mandatory=true
	versionRange="[43,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.fairylights]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.2,1.20)"
	ordering="NONE"
	side="BOTH"
